### ISSUE TITLE
Grunt v1.4 can no longer resolve typescript module paths with tsconfig-paths. It worked fine in v1.3

### ISSUE THREAD

**Issue by darcyparker** [gruntjs/grunt#1729]
I have no issue running Gruntfile.ts with Grunt v1.3 like this: `grunt -r tsconfig-paths/register`

But when I upgrade to v1.4, it fails to find modules I am importing to Gruntfile.ts.  It seems `tsconfig-paths` is not registering because I get errrors like:

```
Loading "Gruntfile.ts" tasks...ERROR
>> Error: Cannot find module 'CommonBuildUtils:makeAllTestsScript'
>> Require stack:
>> - <CurrentDir>Gruntfile.ts
>> - <CurrentDir>/node_modules/grunt/lib/grunt/task.js
>> - <CurrentDir>/node_modules/grunt/lib/grunt.js
>> - <CurrentDir>/node_modules/grunt-cli/bin/grunt
>> - <CurrentDir>/node_modules/grunt/bin/grunt
```

which indicates its not using tsconfig-paths to resolve the module's path.

I am using v3.9.0 (currently latest version) of [tsconfig-paths](https://github.com/dividab/tsconfig-paths)

If I downgrade to v1.3 of grunt, everything works again.

**Comment by vladikoff** [comment]
instead of  -r try --preload: https://github.com/js-cli/js-liftoff#optspreload, https://github.com/js-cli/js-liftoff/commit/e7a969d6706e730d90abb4e24d3cb4d3bce06ddb 

or maybe `-p` should work? 

Sorry this was not evident from the update because it happened downstream.

**Comment by vladikoff** [comment]
I will update the docs now

**Comment by darcyparker** [comment]
I just tried `-p` and `--preload`, and unfortunately it did not work.

I wonder if https://github.com/gruntjs/grunt-known-options/blob/main/index.js is preventing it from being parsed?

See https://github.com/gruntjs/grunt/blob/e86db1c22beb712ae6a504c864fa52425f0724fb/lib/grunt/cli.js#L45

**Comment by vladikoff** [comment]
@darcyparker try https://github.com/gruntjs/grunt/releases/tag/v1.4.1

**Comment by darcyparker** [comment]
Thanks for updating `grunt-known-options`.  Unfortunately it is still not working.  I ran `ndb` and verified `--preload` is parsing `tsconfig-paths/register`.  It seems there is an additional problem.

Could this be it?
https://github.com/gruntjs/grunt-cli/blob/main/bin/grunt#L49

There is no `options.require` now.

**Comment by vladikoff** [comment]
@darcyparker ah so many places to update, I will fix it up soon , thanks for debugging this with me :)

**Comment by vladikoff** [comment]
@darcyparker try https://github.com/gruntjs/grunt-cli/releases/tag/v1.4.3
