### ISSUE TITLE
Error findup-sync not found with grunt-cli 0.1.13

### ISSUE THREAD

**Issue by ManasaVTR** [gruntjs/grunt#1783]
We have been working with grunt-cli version 0.1.13 , node version - 6.17.1, npm version-3.10.10
While running grunt commands we are seeing dependency not  found errors  even though these modules are present in node_modules.
Can anyone help us resolving this issue ?
Error while running grunt --help
Cannot find module 'findup-sync'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\6110853\AppData\Roaming\nvm\v6.17.1\node_modules\grunt-cli\bin\grunt:8:14)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
